services:
  app:
    build: .
    container_name: Farpost_java_intership_test_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/api_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRE_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRE_USER_PASSWORD}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6380:6379"
    restart: unless-stopped
    command: ["redis-server"]

volumes:
  pg_data:
